### ISSUE TITLE
Loading genome scale model 

### ISSUE THREAD

**Issue by yzongy** [jcrozum/pystablemotifs#72] opened 2022-02-10 13:28 UTC
Hi! It's great to see a tool developed for large scale boolean networks analysis.

I was trying to use pystablemotifs to analyse a GRN boolean model with about 2500 nodes. But I found it took a very long time to just load the booleannetwork.txt file. Just wondering if there is any hint to accelerate this process?

Best,

Bill

**Comment by jcrozum** [comment] 2022-02-10 21:10
Hi Bill! I assume you're talking about running the command `pystablemotifs.format.import_primes('/.booleannetwork.txt')`? This can indeed be quite slow when the update functions are very large, i.e., when there are genes that are regulated by a large number of other genes. Unfortunately, there is no easy way to solve this issue in general. One "trick" that might help is to introduce intermediate variables for genes that have large update functions. For example, on a smaller scale,

```
X_A*= X_B & X_C & X_D & X_E & X_F | X_G & X_H & X_K
```
could be replaced by
```
X_A*= X_Y  |  X_Z
X_Y*= X_B & X_C & X_D & X_E & X_F 
X_Z*= X_G & X_H & X_K
```
As long as X_Y* and X_Z* don't share any variables, this is unlikely to have any effect on the attractor repertoire and should give a fairly sizable improvement on how long it takes to import the rule. 

The downside of using this trick is that one of the steps in the attractor finding algorithm can sometimes attempt to undo the trick, which is very slow. If it is taking too long to build the attractor repertoire, I suggest using the `MPBN_update=True` option in the `AttractorRepertoire.from_primes` function. This may miss certain very fragile oscillations called motif-avoidant attractors, but oscillations of this type are extremely rare in asynchronously updated BNs, and are nonexistent in the MPBN update scheme described by [Paulevé et al. in 2020](https://doi.org/10.1038/s41467-020-18112-5) (hence the name of the option).

**Comment by jcrozum** [comment] 2022-02-11 00:14
I've taken a quick look, and I am fairly certain that the problem is that some of the rules have too many variables in them for the code to process in a reasonable amount of time. Once you get to a dozen or so input variables for a rule, the importing process slows down dramatically. I am able to load a subset of the file just fine, so the formatting is not the issue. I am not able to load some of the longer rules unless I break them up using the trick I outlined above. For example, I am not able to load this:
```
YGL008C_fc*=  (YHR084W_fc) or (YIL131C_fc) or (YER040W_fc) or (YMR043W_fc) or (YGL073W_fc) or (YHR206W_fc) or (YHR178W_fc) or (YMR037C_fc) or (YNL216W_fc) or (YJR060W_fc) and not (YNL027W_fc or YDL056W_fc or YDL020C_fc or YDR146C_fc or YEL009C_fc or YKL185W_fc)
```
But I am able to load this in less than a second:
```
YGL008C_fc*=  (YHR084W_fc) or (YIL131C_fc) or (YER040W_fc) or (YMR043W_fc) or X1 or X2
X1*=(YGL073W_fc) or (YHR206W_fc) or (YHR178W_fc) or (YMR037C_fc) or (YNL216W_fc)
X2*= (YJR060W_fc) and not (YNL027W_fc or YDL056W_fc or YDL020C_fc or YDR146C_fc or YEL009C_fc or YKL185W_fc)
```
Both versions will give the same attractors, so I recommend breaking up the rules like this if they have more than 10 or so inputs.


As an aside, I do want to caution you that
```
X_A*= X_Y  |  X_Z
```
is fine by itself, but adding the lines
```
X_Y*=
X_Z*=
```
will cause a crash (I did not see any such lines included in the example you sent me though, so it should be OK). If you leave the update function undefined for a variable, it will be treated as source node, i.e.,

```
X_A*= X_Y  |  X_Z
```
by itself is equivalent to 
```
X_A*= X_Y  |  X_Z
X_Y*=X_Y
X_Z*=X_Z
```

That being said, if you have a lot of these, then you might want to specify values for the unregulated genes explicitly, e.g.,`X_Z*=1`, so that the code won't try to find attractors for all possible source input combinations.

**Comment by yzongy** [comment] 2022-02-15 14:50
Thanks, Jordan!

I have written a parser to split lines as you suggested and also specified unregulated genes. But when an error raised when I was importing the file with `pystablemotifs.format.import_primes`:

> ERROR failed to run bnet2primes: cmd=/Users/yzongy/.pyenv/versions/3.9.7/lib/python3.9/site-packages/pyboolnet/binaries/BNetToPrime/BNetToPrime_mac64, return_code=1, out=b'{"Q0050_fc":[[{"YIR018W_fc":0,\x08 \x08},\x08 \x08],[{"YIR018W_fc":1,\x08 \x08},\x08 \x08]],"YAL003W_fc":[[{"YDL056W_fc":0,"YER111C_fc":1,"YHR206W_fc":0,"YKL112W_fc":0,"YNL216W_fc":0,\x08 \x08},{"YDL056W_fc":0,"YEL009C_fc":1,"YHR206W_fc":0,"YKL112W_fc":0,"YNL216W_fc":0,\x08 \x08},{"YAL003W_fc_intermediate_1":0,"YDL056W_fc":0,"YHR206W_fc":0,"YKL112W_fc":0,"YNL216W_fc":0,\x08 \x08},\x08 \x08],[{"YAL003W_fc_intermediate_1":1,"YEL009C_fc":0,"YER111C_fc":0,\x08 \x08},{"YNL216W_fc":1,\x08 \x08},{"YKL112W_fc":1,\x08 \x08},{"YHR206W_fc":1,\x08 \x08},{"YDL056W_fc":1,\x08 \x08},\x08 \x08]

Was it caused by some conflicts or the wrong formatting of the input file?
[processed_output_boolNet.txt](https://github.com/jcrozum/pystablemotifs/files/8072120/processed_output_boolNet.txt)

**Comment by jcrozum** [comment] 2022-02-15 15:51
It looks like there's a problem with the formatting: the intermediate node rules have mismatched parentheses, e.g.,
```
YHR087W_fc_intermediate_1*= YIL101C_fc) or (YMR172W_fc) or (YKL062W_fc) or (YIL131C_fc)
```
should be
```
YHR087W_fc_intermediate_1*= (YIL101C_fc) or (YMR172W_fc) or (YKL062W_fc) or (YIL131C_fc)
```
I saw this in all the intermediate rules I checked in the file you attached.

**Comment by yzongy** [comment] 2022-02-16 22:30
Hey Jordan, it works!

I have fixed the missing parentheses and also break long "and not" lines.  

For the GRN network with about 3500 genes, it took about 35mins to import the file and calculate attractors.

I also created a PDF file to visualise the network but it's a very long figure, which layout engine can make this more compact and easier to put on a single page?

**Comment by jcrozum** [comment] 2022-02-16 22:44
Great, I'm glad it worked for you!

**Closed by jcrozum** 2022-02-16 22:44 UTC
